import type { Sponsorship, Offer, Task, Deadline, PipelineDeal, Deal, SponsorshipDeliverables, LibraryFile, InboxItem } from "./types"

export const mockSponsorships: Sponsorship[] = [
  {
    id: "1",
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    status: "active",
    progress: 65,
    value: 15000,
    startDate: "2025-03-01",
    endDate: "2025-05-15",
    deliverables: 8,
    completedDeliverables: 5,
  },
  {
    id: "2",
    eventName: "Hackathon Weekend",
    organization: "MIT Computer Science Club",
    status: "active",
    progress: 40,
    value: 8000,
    startDate: "2025-02-15",
    endDate: "2025-04-20",
    deliverables: 5,
    completedDeliverables: 2,
  },
  {
    id: "3",
    eventName: "Cultural Festival",
    organization: "UCLA Student Union",
    status: "pending",
    progress: 0,
    value: 5000,
    startDate: "2025-04-01",
    endDate: "2025-06-30",
    deliverables: 6,
    completedDeliverables: 0,
  },
]

export const mockOffers: Offer[] = [
  {
    id: "1",
    eventName: "Summer Music Festival",
    organization: "Berkeley Music Society",
    organizerName: "Sarah Johnson",
    type: "sent",
    amount: 12000,
    offerType: "money",
    status: "pending",
    date: "2025-01-15",
  },
  {
    id: "2",
    eventName: "Entrepreneurship Summit",
    organization: "Harvard Business Club",
    organizerName: "Emily Rodriguez",
    type: "received",
    amount: 20000,
    offerType: "money",
    status: "pending",
    date: "2025-01-20",
  },
  {
    id: "3",
    eventName: "Sports Day 2025",
    organization: "Yale Athletics",
    organizerName: "Mike Chen",
    type: "sent",
    amount: 7500,
    offerType: "money",
    status: "pending",
    date: "2025-01-18",
  },
  {
    id: "4",
    eventName: "Tech Innovation Week",
    organization: "MIT Innovation Lab",
    organizerName: "David Kim",
    type: "received",
    offerType: "product",
    status: "pending",
    date: "2025-01-22",
  },
  {
    id: "5",
    eventName: "Cultural Festival",
    organization: "UCLA Student Union",
    organizerName: "Lisa Wang",
    type: "sent",
    offerType: "booth",
    status: "pending",
    date: "2025-01-19",
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Deliver branded merchandise",
    sponsorship: "Spring Tech Conference 2025",
    dueDate: "2025-02-28",
    status: "in-progress",
    priority: "high",
  },
  {
    id: "2",
    title: "Set up exhibition booth",
    sponsorship: "Spring Tech Conference 2025",
    dueDate: "2025-03-05",
    status: "pending",
    priority: "high",
  },
  {
    id: "3",
    title: "Provide speaker for opening keynote",
    sponsorship: "Hackathon Weekend",
    dueDate: "2025-03-10",
    status: "pending",
    priority: "medium",
  },
  {
    id: "4",
    title: "Submit logo for event materials",
    sponsorship: "Cultural Festival",
    dueDate: "2025-03-15",
    status: "pending",
    priority: "low",
  },
  {
    id: "5",
    title: "Review and approve final design",
    sponsorship: "Hackathon Weekend",
    dueDate: "2025-02-25",
    status: "completed",
    priority: "medium",
  },
]

export const mockDeadlines: Deadline[] = [
  {
    id: "1",
    title: "Final payment due",
    sponsorship: "Spring Tech Conference 2025",
    dueDate: "2025-03-01",
    type: "payment",
    daysUntil: 5,
  },
  {
    id: "2",
    title: "Deliver promotional materials",
    sponsorship: "Hackathon Weekend",
    dueDate: "2025-03-08",
    type: "deliverable",
    daysUntil: 12,
  },
  {
    id: "3",
    title: "Booth setup review",
    sponsorship: "Spring Tech Conference 2025",
    dueDate: "2025-03-03",
    type: "review",
    daysUntil: 7,
  },
  {
    id: "4",
    title: "Content approval deadline",
    sponsorship: "Cultural Festival",
    dueDate: "2025-03-20",
    type: "review",
    daysUntil: 24,
  },
]

export const mockPipelineDeals: PipelineDeal[] = [
  // Pending
  {
    id: "p1",
    eventName: "Summer Music Festival",
    organization: "Berkeley Music Society",
    stage: "pending",
    value: 12000,
    probability: 30,
    contactPerson: "Sarah Johnson",
    contactEmail: "sarah@berkeley.edu",
    lastActivity: "2025-01-15",
    nextAction: "Follow up on initial proposal",
    notes: "Waiting for initial response",
  },
  {
    id: "p2",
    eventName: "Sports Day 2025",
    organization: "Yale Athletics",
    stage: "pending",
    value: 7500,
    probability: 25,
    contactPerson: "Mike Chen",
    contactEmail: "mike@yale.edu",
    lastActivity: "2025-01-18",
    nextAction: "Send sponsorship package",
  },
  // Negotiation
  {
    id: "p3",
    eventName: "Entrepreneurship Summit",
    organization: "Harvard Business Club",
    stage: "negotiation",
    value: 20000,
    probability: 60,
    contactPerson: "Emily Rodriguez",
    contactEmail: "emily@harvard.edu",
    lastActivity: "2025-01-22",
    nextAction: "Review contract terms",
    notes: "Discussing sponsorship tier options",
  },
  {
    id: "p4",
    eventName: "Tech Innovation Week",
    organization: "MIT Innovation Lab",
    stage: "negotiation",
    value: 18000,
    probability: 55,
    contactPerson: "David Kim",
    contactEmail: "david@mit.edu",
    lastActivity: "2025-01-20",
    nextAction: "Schedule call to finalize details",
  },
  // Approved
  {
    id: "p5",
    eventName: "Cultural Festival",
    organization: "UCLA Student Union",
    stage: "approved",
    value: 5000,
    probability: 90,
    contactPerson: "Lisa Wang",
    contactEmail: "lisa@ucla.edu",
    lastActivity: "2025-01-25",
    nextAction: "Prepare deliverables",
    notes: "Contract signed, awaiting start date",
  },
  // Active
  {
    id: "p6",
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    stage: "active",
    value: 15000,
    probability: 100,
    contactPerson: "John Smith",
    contactEmail: "john@stanford.edu",
    lastActivity: "2025-01-28",
    nextAction: "Monitor progress",
    notes: "In progress, 65% complete",
  },
  {
    id: "p7",
    eventName: "Hackathon Weekend",
    organization: "MIT Computer Science Club",
    stage: "active",
    value: 8000,
    probability: 100,
    contactPerson: "Alex Brown",
    contactEmail: "alex@mit.edu",
    lastActivity: "2025-01-27",
    nextAction: "Deliver branded materials",
  },
  // Completed
  {
    id: "p8",
    eventName: "Winter Charity Gala",
    organization: "Princeton Alumni Association",
    stage: "completed",
    value: 10000,
    probability: 100,
    contactPerson: "Maria Garcia",
    contactEmail: "maria@princeton.edu",
    lastActivity: "2024-12-15",
    notes: "Successfully completed, all deliverables met",
  },
  {
    id: "p9",
    eventName: "Fall Career Fair",
    organization: "Columbia Career Services",
    stage: "completed",
    value: 12000,
    probability: 100,
    contactPerson: "Robert Taylor",
    contactEmail: "robert@columbia.edu",
    lastActivity: "2024-11-20",
    notes: "Event completed successfully",
  },
]

export const mockDeals: Deal[] = [
  {
    id: "deal1",
    eventName: "Spring Tech Conference 2025",
    organizerName: "John Smith",
    organizerEmail: "john@stanford.edu",
    organization: "Stanford University",
    status: "pending",
    packageDetails: {
      items: [
        "Premium booth space (10x10 ft)",
        "Logo placement on all event materials",
        "Social media mentions (5 posts)",
        "Branded swag distribution",
        "Networking event access",
        "Keynote speaker mention",
      ],
      value: 15000,
      benefits: [
        "Brand visibility to 3,000+ attendees",
        "Lead generation opportunities",
        "Media coverage inclusion",
        "Access to attendee contact list",
        "Post-event analytics report",
      ],
    },
    termsAndConditions: [
      "Payment: 50% upfront, 50% upon event completion",
      "Deliverables must be completed 2 weeks before event",
      "Logo and branding materials must be approved by sponsor",
      "Cancellation policy: 30 days notice required for full refund",
      "Force majeure: Event cancellation due to circumstances beyond control",
      "Intellectual property: Sponsor retains all rights to provided materials",
    ],
    contractPdfUrl: "/contracts/spring-tech-2025.pdf",
    proposalSentDate: "2025-01-15",
    sponsorViewedDate: "2025-01-16",
    timeline: [
      {
        event: "Proposal Sent",
        date: "2025-01-15",
        description: "Event organizer sent sponsorship proposal",
      },
      {
        event: "Sponsor Viewed",
        date: "2025-01-16",
        description: "You viewed the proposal",
      },
    ],
  },
  {
    id: "deal2",
    eventName: "Hackathon Weekend",
    organizerName: "Alex Brown",
    organizerEmail: "alex@mit.edu",
    organization: "MIT Computer Science Club",
    status: "changes_requested",
    packageDetails: {
      items: [
        "Standard booth space (8x8 ft)",
        "Logo on event website",
        "Social media shout-out (3 posts)",
        "Product showcase opportunity",
      ],
      value: 8000,
      benefits: [
        "Access to 500+ tech students",
        "Recruitment opportunities",
        "Brand awareness in tech community",
      ],
    },
    termsAndConditions: [
      "Payment: Full amount due 1 week before event",
      "Booth setup: Sponsor responsible for setup and teardown",
      "Materials: Must be provided 1 week in advance",
      "Cancellation: 14 days notice for 50% refund",
    ],
    proposalSentDate: "2025-01-10",
    sponsorViewedDate: "2025-01-11",
    decisionDate: "2025-01-12",
    timeline: [
      {
        event: "Proposal Sent",
        date: "2025-01-10",
        description: "Event organizer sent sponsorship proposal",
      },
      {
        event: "Sponsor Viewed",
        date: "2025-01-11",
        description: "You viewed the proposal",
      },
      {
        event: "Changes Requested",
        date: "2025-01-12",
        description: "You requested modifications to the package",
      },
    ],
  },
]

export const mockSponsorshipDeliverables: SponsorshipDeliverables[] = [
  {
    sponsorshipId: "1",
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    deliverables: [
      {
        id: "d1",
        title: "Logo placement on website",
        status: "approved",
        dueDate: "2025-02-15",
        description: "Place sponsor logo on event website homepage and sponsors page",
        proofSubmissions: [
          {
            id: "p1",
            submittedDate: "2025-02-10",
            files: ["website-screenshot.png", "logo-placement.pdf"],
            notes: "Logo placed on homepage and sponsors page as requested",
          },
        ],
      },
      {
        id: "d2",
        title: "Social media posts (5 posts)",
        status: "submitted",
        dueDate: "2025-02-20",
        description: "Post 5 social media mentions across Facebook, Twitter, and Instagram",
        proofSubmissions: [
          {
            id: "p2",
            submittedDate: "2025-02-18",
            files: ["facebook-post-1.png", "twitter-post-2.png", "instagram-post-3.png"],
            notes: "3 posts submitted, 2 more coming before deadline",
          },
        ],
      },
      {
        id: "d3",
        title: "Booth setup at event",
        status: "not_started",
        dueDate: "2025-03-01",
        description: "Set up 10x10 ft exhibition booth at event venue",
        proofSubmissions: [],
      },
      {
        id: "d4",
        title: "Branded swag distribution",
        status: "submitted",
        dueDate: "2025-02-25",
        description: "Distribute branded merchandise to 500 attendees",
        proofSubmissions: [
          {
            id: "p3",
            submittedDate: "2025-02-22",
            files: ["swag-inventory-list.pdf", "distribution-photos.zip"],
            notes: "All 500 items prepared and ready for distribution",
          },
        ],
      },
      {
        id: "d5",
        title: "Keynote speaker mention",
        status: "approved",
        dueDate: "2025-03-05",
        description: "Mention sponsor during opening keynote speech",
        proofSubmissions: [
          {
            id: "p4",
            submittedDate: "2025-03-03",
            files: ["keynote-script.pdf"],
            notes: "Sponsor mention included in keynote script",
          },
        ],
      },
      {
        id: "d6",
        title: "Networking event access",
        status: "not_started",
        dueDate: "2025-03-10",
        description: "Provide access to exclusive networking event for sponsor team",
        proofSubmissions: [],
      },
      {
        id: "d7",
        title: "Post-event analytics report",
        status: "rejected",
        dueDate: "2025-03-15",
        description: "Provide detailed analytics report with attendee demographics and engagement metrics",
        proofSubmissions: [
          {
            id: "p5",
            submittedDate: "2025-03-12",
            files: ["analytics-report-v1.pdf"],
            notes: "Initial report submitted",
          },
        ],
      },
      {
        id: "d8",
        title: "Media coverage inclusion",
        status: "submitted",
        dueDate: "2025-03-20",
        description: "Include sponsor in all press releases and media coverage",
        proofSubmissions: [
          {
            id: "p6",
            submittedDate: "2025-03-18",
            files: ["press-release-1.pdf", "media-mentions.pdf"],
            notes: "Sponsor mentioned in 3 press releases and 2 media articles",
          },
        ],
      },
    ],
  },
  {
    sponsorshipId: "2",
    eventName: "Hackathon Weekend",
    organization: "MIT Computer Science Club",
    deliverables: [
      {
        id: "d9",
        title: "Logo on event website",
        status: "approved",
        dueDate: "2025-02-10",
        proofSubmissions: [
          {
            id: "p7",
            submittedDate: "2025-02-08",
            files: ["website-logo.png"],
          },
        ],
      },
      {
        id: "d10",
        title: "Social media shout-out (3 posts)",
        status: "submitted",
        dueDate: "2025-02-15",
        proofSubmissions: [
          {
            id: "p8",
            submittedDate: "2025-02-13",
            files: ["social-posts.zip"],
          },
        ],
      },
      {
        id: "d11",
        title: "Product showcase opportunity",
        status: "not_started",
        dueDate: "2025-02-25",
        proofSubmissions: [],
      },
      {
        id: "d12",
        title: "Booth space (8x8 ft)",
        status: "not_started",
        dueDate: "2025-03-01",
        proofSubmissions: [],
      },
    ],
  },
]


export const mockLibraryFiles: LibraryFile[] = [
  {
    id: "f1",
    name: "Event Contract - Spring Tech Conference.pdf",
    type: "contract",
    size: 2456789,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-01-20",
    uploadedBy: "John Smith",
    url: "/files/contracts/spring-tech-2025.pdf",
    description: "Signed sponsorship agreement contract",
  },
  {
    id: "f2",
    name: "Logo Placement Screenshot.png",
    type: "image",
    size: 1234567,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-02-10",
    uploadedBy: "John Smith",
    url: "/files/proofs/logo-placement.png",
    thumbnailUrl: "/files/proofs/logo-placement-thumb.png",
    description: "Proof of logo placement on event website",
  },
  {
    id: "f3",
    name: "Social Media Posts.zip",
    type: "proof",
    size: 3456789,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-02-18",
    uploadedBy: "John Smith",
    url: "/files/proofs/social-posts.zip",
    description: "Screenshots of 5 social media posts",
  },
  {
    id: "f4",
    name: "Event Analytics Report Q1 2025.pdf",
    type: "report",
    size: 4567890,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-03-15",
    uploadedBy: "John Smith",
    url: "/files/reports/analytics-q1-2025.pdf",
    description: "Post-event analytics and engagement metrics",
  },
  {
    id: "f5",
    name: "Booth Setup Video.mp4",
    type: "video",
    size: 12345678,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-03-01",
    uploadedBy: "John Smith",
    url: "/files/videos/booth-setup.mp4",
    thumbnailUrl: "/files/videos/booth-setup-thumb.jpg",
    description: "Video documentation of booth setup",
  },
  {
    id: "f6",
    name: "Hackathon Contract Agreement.pdf",
    type: "contract",
    size: 1890123,
    eventName: "Hackathon Weekend",
    organization: "MIT Computer Science Club",
    sponsorshipId: "2",
    uploadedDate: "2025-01-25",
    uploadedBy: "Alex Brown",
    url: "/files/contracts/hackathon-2025.pdf",
    description: "Signed sponsorship contract",
  },
  {
    id: "f7",
    name: "Website Logo Placement.pdf",
    type: "proof",
    size: 987654,
    eventName: "Hackathon Weekend",
    organization: "MIT Computer Science Club",
    sponsorshipId: "2",
    uploadedDate: "2025-02-08",
    uploadedBy: "Alex Brown",
    url: "/files/proofs/website-logo.pdf",
    description: "Screenshot of logo on event website",
  },
  {
    id: "f8",
    name: "Social Media Posts Collection.zip",
    type: "proof",
    size: 2345678,
    eventName: "Hackathon Weekend",
    organization: "MIT Computer Science Club",
    sponsorshipId: "2",
    uploadedDate: "2025-02-13",
    uploadedBy: "Alex Brown",
    url: "/files/proofs/social-collection.zip",
    description: "3 social media posts with sponsor mentions",
  },
  {
    id: "f9",
    name: "Event Photos Gallery.zip",
    type: "image",
    size: 5678901,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-03-10",
    uploadedBy: "John Smith",
    url: "/files/images/event-photos.zip",
    thumbnailUrl: "/files/images/event-photos-thumb.jpg",
    description: "Event photos featuring sponsor booth and branding",
  },
  {
    id: "f10",
    name: "Final Sponsorship Report.pdf",
    type: "report",
    size: 3456789,
    eventName: "Hackathon Weekend",
    organization: "MIT Computer Science Club",
    sponsorshipId: "2",
    uploadedDate: "2025-03-20",
    uploadedBy: "Alex Brown",
    url: "/files/reports/final-report.pdf",
    description: "Comprehensive post-event sponsorship report",
  },
  {
    id: "f11",
    name: "Branded Swag Distribution Photos.jpg",
    type: "image",
    size: 2345678,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-02-22",
    uploadedBy: "John Smith",
    url: "/files/images/swag-distribution.jpg",
    thumbnailUrl: "/files/images/swag-distribution-thumb.jpg",
    description: "Photos of branded merchandise distribution",
  },
  {
    id: "f12",
    name: "Keynote Speech Video.mp4",
    type: "video",
    size: 15678901,
    eventName: "Spring Tech Conference 2025",
    organization: "Stanford University",
    sponsorshipId: "1",
    uploadedDate: "2025-03-05",
    uploadedBy: "John Smith",
    url: "/files/videos/keynote-speech.mp4",
    thumbnailUrl: "/files/videos/keynote-thumb.jpg",
    description: "Video of keynote speech with sponsor mention",
  },
]

export const mockInboxItems: InboxItem[] = [
  {
    id: "inbox1",
    type: "message",
    eventName: "Spring Tech Conference 2025",
    sponsorshipId: "1",
    sponsorshipItem: ":30 TV Spot | Basketball",
    organization: "Stanford University",
    organizerName: "Samantha",
    organizerInitials: "SA",
    lastMessage: "Can we get an additional 16:9 ratio version for digital displays?",
    timestamp: "2025-01-28T10:30:00Z",
    relativeTime: "1h",
    isUnread: true,
    statusIcon: "message",
    description: "Prime branding at ASU's flagship community event the Sun Devils Festival. Prime branding.",
    specs: {
      format: "Apple ProRes 422 HQ or H.264—ProRes 422 HQ is preferred for its high-quality retention, while H.264 is a more compressed option suitable for digital platforms.",
      dimensions: "1920x1080 (16:9), 1080x1920 (9:16)",
      requirements: ["Logo must be visible", "Brand colors maintained", "HD quality"],
    },
    attachedFiles: [
      {
        id: "af1",
        name: "tv-spot-final.mp4",
        type: "video",
        url: "/files/videos/tv-spot-final.mp4",
        thumbnailUrl: "/files/videos/tv-spot-thumb.jpg",
      },
    ],
    associatedBrands: [
      { id: "b1", name: "BOND STREET", logoUrl: "/brands/bond-street.png" },
      { id: "b2", name: "BMW", logoUrl: "/brands/bmw.png" },
      { id: "b3", name: "A", logoUrl: "/brands/a.png" },
      { id: "b4", name: "Coca-Cola", logoUrl: "/brands/coca-cola.png" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Add the design for these banners",
        dueDate: "2025-02-28",
        status: "completed",
        priority: "high",
      },
      {
        id: "t2",
        title: "Add the design for these banners",
        dueDate: "2025-02-28",
        status: "pending",
        priority: "high",
      },
      {
        id: "t3",
        title: "Additional 16:9 ratio",
        dueDate: "2025-03-01",
        status: "pending",
        priority: "medium",
      },
    ],
    messages: [
      {
        id: "m1",
        author: "Samantha",
        authorInitials: "SA",
        content: "Can we get an additional 16:9 ratio version for digital displays?",
        timestamp: "2025-01-28T10:30:00Z",
        relativeTime: "1h",
      },
    ],
    activityTimeline: [
      {
        id: "a1",
        event: "Message sent",
        timestamp: "2025-01-28T10:30:00Z",
        user: "Samantha",
      },
    ],
  },
  {
    id: "inbox2",
    type: "update",
    eventName: "Spring Tech Conference 2025",
    sponsorshipId: "1",
    sponsorshipItem: "$5,000 Ticket Bank | Football",
    organization: "Stanford University",
    organizerName: "Alex",
    organizerInitials: "AR",
    lastUpdate: "Alex made a change to this asset",
    timestamp: "2025-01-27T16:00:00Z",
    relativeTime: "18h",
    isUnread: false,
    statusIcon: "update",
    description: "Ticket bank allocation for premium seating at football games",
    tasks: [
      {
        id: "t4",
        title: "Review ticket allocation",
        dueDate: "2025-02-15",
        status: "pending",
        priority: "medium",
      },
    ],
    activityTimeline: [
      {
        id: "a2",
        event: "Asset updated",
        timestamp: "2025-01-27T16:00:00Z",
        user: "Alex",
      },
    ],
  },
  {
    id: "inbox3",
    type: "mention",
    eventName: "Spring Tech Conference 2025",
    sponsorshipId: "1",
    sponsorshipItem: "10 x 10 Activation Space | Theatre",
    organization: "Stanford University",
    organizerName: "Hannah",
    organizerInitials: "HA",
    lastMessage: "Hannah mentioned you in a task",
    timestamp: "2025-01-27T14:00:00Z",
    relativeTime: "18h",
    isUnread: true,
    statusIcon: "mention",
    description: "Activation space for brand engagement at theatre events",
    tasks: [
      {
        id: "t5",
        title: "Setup activation space design",
        dueDate: "2025-02-20",
        status: "pending",
        priority: "high",
      },
    ],
    messages: [
      {
        id: "m2",
        author: "Hannah",
        authorInitials: "HA",
        content: "@you Please review the activation space requirements",
        timestamp: "2025-01-27T14:00:00Z",
        relativeTime: "18h",
      },
    ],
    activityTimeline: [
      {
        id: "a3",
        event: "You were mentioned",
        timestamp: "2025-01-27T14:00:00Z",
        user: "Hannah",
      },
    ],
  },
  {
    id: "inbox4",
    type: "update",
    eventName: "Spring Tech Conference 2025",
    sponsorshipId: "1",
    sponsorshipItem: "365CU Insider Content | Basketball",
    organization: "Stanford University",
    organizerName: "Jeff",
    organizerInitials: "JE",
    lastUpdate: "Jeff made a change to this asset",
    timestamp: "2025-01-27T12:00:00Z",
    relativeTime: "18h",
    isUnread: true,
    statusIcon: "warning",
    description: "Exclusive insider content for basketball season",
    tasks: [
      {
        id: "t6",
        title: "Approve content changes",
        dueDate: "2025-02-10",
        status: "overdue",
        priority: "high",
      },
    ],
    activityTimeline: [
      {
        id: "a4",
        event: "Asset updated",
        timestamp: "2025-01-27T12:00:00Z",
        user: "Jeff",
      },
    ],
  },
  {
    id: "inbox5",
    type: "message",
    eventName: "Spring Tech Conference 2025",
    sponsorshipId: "1",
    sponsorshipItem: "Activation Fund | Basketball",
    organization: "Stanford University",
    organizerName: "Damien",
    organizerInitials: "DA",
    lastMessage: "Damien replied to your message",
    timestamp: "2025-01-27T10:00:00Z",
    relativeTime: "18h",
    isUnread: false,
    statusIcon: "message",
    description: "Funding allocation for activation activities",
    messages: [
      {
        id: "m3",
        author: "Damien",
        authorInitials: "DA",
        content: "Great thank you for the update",
        timestamp: "2025-01-27T10:00:00Z",
        relativeTime: "18h",
      },
    ],
    activityTimeline: [
      {
        id: "a5",
        event: "Message received",
        timestamp: "2025-01-27T10:00:00Z",
        user: "Damien",
      },
    ],
  },
  {
    id: "inbox6",
    type: "proof_submission",
    eventName: "Spring Tech Conference 2025",
    sponsorshipId: "1",
    sponsorshipItem: "Logo Placement Screenshot",
    organization: "Stanford University",
    organizerName: "John Smith",
    organizerInitials: "JS",
    lastUpdate: "Proof submitted for review",
    timestamp: "2025-01-27T08:00:00Z",
    relativeTime: "1d",
    isUnread: true,
    statusIcon: "proof",
    description: "Screenshot proof of logo placement on event website",
    proofData: {
      id: "proof1",
      title: "Logo Placement Screenshot",
      status: "pending",
      submittedDate: "2025-01-27T08:00:00Z",
      files: ["logo-placement.png", "website-screenshot.pdf"],
    },
    attachedFiles: [
      {
        id: "af2",
        name: "logo-placement.png",
        type: "image",
        url: "/files/proofs/logo-placement.png",
        thumbnailUrl: "/files/proofs/logo-placement-thumb.png",
      },
    ],
    activityTimeline: [
      {
        id: "a6",
        event: "Proof submitted",
        timestamp: "2025-01-27T08:00:00Z",
        user: "John Smith",
      },
    ],
  },
  {
    id: "inbox7",
    type: "task_update",
    eventName: "Hackathon Weekend",
    sponsorshipId: "2",
    sponsorshipItem: "Center Ice Logo | Football",
    organization: "MIT Computer Science Club",
    organizerName: "Alex Brown",
    organizerInitials: "AB",
    lastUpdate: "Task status updated",
    timestamp: "2025-01-26T20:00:00Z",
    relativeTime: "1d",
    isUnread: false,
    statusIcon: "task",
    description: "Center ice logo placement for football events",
    tasks: [
      {
        id: "t7",
        title: "Review logo placement",
        dueDate: "2025-02-05",
        status: "completed",
        priority: "medium",
      },
    ],
    activityTimeline: [
      {
        id: "a7",
        event: "Task completed",
        timestamp: "2025-01-26T20:00:00Z",
        user: "Alex Brown",
      },
    ],
  },
  {
    id: "inbox8",
    type: "message",
    eventName: "Hackathon Weekend",
    sponsorshipId: "2",
    sponsorshipItem: "Coach's Show :30 Commercial Spot | Basketball",
    organization: "MIT Computer Science Club",
    organizerName: "Alex Brown",
    organizerInitials: "AB",
    lastMessage: "Great thank you for the update",
    timestamp: "2025-01-26T18:00:00Z",
    relativeTime: "1d",
    isUnread: false,
    statusIcon: "message",
    description: "30-second commercial spot for coach's show",
    messages: [
      {
        id: "m4",
        author: "Alex Brown",
        authorInitials: "AB",
        content: "Great thank you for the update",
        timestamp: "2025-01-26T18:00:00Z",
        relativeTime: "1d",
      },
    ],
    activityTimeline: [
      {
        id: "a8",
        event: "Message received",
        timestamp: "2025-01-26T18:00:00Z",
        user: "Alex Brown",
      },
    ],
  },
  {
    id: "inbox9",
    type: "proof_submission",
    eventName: "Spring Tech Conference 2025",
    sponsorshipId: "1",
    sponsorshipItem: "Social Media Posts Collection",
    organization: "Stanford University",
    organizerName: "John Smith",
    organizerInitials: "JS",
    lastUpdate: "New proof submission for social media posts",
    timestamp: "2025-01-26T14:00:00Z",
    relativeTime: "2d",
    isUnread: true,
    statusIcon: "proof",
    description: "Screenshots of social media posts with sponsor mentions",
    proofData: {
      id: "proof2",
      title: "Social Media Posts Collection",
      status: "pending",
      submittedDate: "2025-01-26T14:00:00Z",
      files: ["social-posts.zip"],
    },
    attachedFiles: [
      {
        id: "af3",
        name: "social-posts.zip",
        type: "archive",
        url: "/files/proofs/social-posts.zip",
      },
    ],
    activityTimeline: [
      {
        id: "a9",
        event: "Proof submitted",
        timestamp: "2025-01-26T14:00:00Z",
        user: "John Smith",
      },
    ],
  },
]
